services:
  # Frontend: React app (Static Site)
  - type: web
    name: trading-app-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    branch: main  # Use 'master' if your branch is 'master'
    autoDeploy: true
    plan: free
    region: oregon

  # Backend: Python app (Web Service)
  - type: web
    name: trading-app-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    branch: main  # Use 'master' if your branch is 'master'
    autoDeploy: true
    plan: free
    region: oregon
    envVars:
      - key: PYTHON_VERSION
        value: "3.9"