services:
  # Frontend: React app (Static Site)
  - type: static  # Corrected from 'web' to 'static' for React
    name: trading-app-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    branch: main  # Adjusted to 'main' (common default; change if yours is 'master')
    autoDeploy: true
    plan: free  # Explicitly set to free tier
    region: oregon  # Free tier region

  # Backend: Python app (Web Service)
  - type: web
    name: trading-app-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app  # Updated to use Gunicorn for production
    branch: main  # Adjusted to 'main' (change if yours is 'master')
    autoDeploy: true
    plan: free  # Explicitly set to free tier
    region: oregon  # Free tier region
    envVars:
      - key: PYTHON_VERSION
        value: "3.9"  # Matches your specification